version: 2
jobs:
  conda-linux:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: mkdir -p workspace
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - run: bash miniconda.sh -b -p workspace/miniconda
      - persist_to_workspace:
          root: workspace
          paths:
            - miniconda
  create-env-27:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - attach_workspace:
          at: ./workspace
      - run: export PATH=workspace/miniconda/bin:$PATH"
      - run: conda config --set always_yes yes --set changeps1 no
      - run: conda update -q conda
      - run: conda create -q --prefix workspace/test-environment python=2.7 pip
      - persist_to_workspace:
          root: workspace
          paths:
            - test-environment
  test:
    docker:
      - image: buildpack-deps:trusty
    environment:
      TEST_NWB_FILES: skip
      TEST_OBSERVATORY_EXPERIMENT_PLOTS_DATA: skip
      TEST_API_ENDPOINT: http://api.brain-map.org 
      TEST_COMPLETE: false
    steps:
      - attach_workspace:
          at: ./workspace
      - run: source activate workspace/test-environment
      - run: pip install -r test_requirements.txt
      - run: pip install .
      - run: make test

workflows:
  version: 2
  linux-27:
    jobs:
      - conda-linux
      - create-env-27:
          requires:
            - conda-linux
      - test:
          requires:
            - create-env-27
