version: 2
jobs:
  build-linux-27:
    docker:
      - image: buildpack-deps:trusty
        environment:
          TEST_PYTHON_VERSION: 2.7
    steps:
      - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  build-linux-36:
    docker:
      - image: buildpack-deps:trusty
        environment:
          TEST_PYTHON_VERSION: 3.6
    steps:
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  install:
    docker:
      - image: buildpack-deps:trusty
    environment:
      TEST_NWB_FILES: skip
      TEST_OBSERVATORY_EXPERIMENT_PLOTS_DATA: skip
      TEST_API_ENDPOINT: http://api.brain-map.org 
      TEST_COMPLETE: false
    steps:
      - export PATH="$HOME/miniconda/bin:$PATH"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda create -q -n test-environment python=$TEST_PYTHON_VERSION pip
      - source activate test-environment
      - pip install -r test_requirements.txt
      - pip install .
  test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - make test

workflows:
  version: 2
  linux-27:
    jobs:
      - build-linux-27
      - install
      - test
  linux-36:
    jobs:
      - build-linux-36
      - install
      - test
